### ISSUE TITLE
Formatting command using option variables 

### ISSUE THREAD

**Issue by haryle** [haryle/PyMake#49]
Current split command based on " " and then rejoin, ignoring "" i.e. 

`
string = " ".join([item for item in string.split(" ") if item]) 
`
Reason for doing this is to format option variables that takes None value if not parsed - i.e. 

```
var:
    option:
         interactive: -i
    cmd:
        - python $(interactive) script.py 
```

If `interactive` is not provided, ideally the command should be formatted to `python script.py` instead of `python  script.py`. If interactive is provided, the formatted comand should be `python -i script.py`.

However, the current method would indiscriminately split strings. i.e. if cmd is like this:

```
python $(interactive) -c "print('Hello    World')
```

This might unintentionally split the space inside the print statement, which is not ideal.
