### ISSUE TITLE
Default value for basic variables not registered

### ISSUE THREAD

**Issue by haryle** [haryle/PyMake#52]
```
plot:
    var: 
        basic: 
             bhp_class:0
       option:
             interactive: "-i"
    cmd:
       - python $(interactive) scripts/plot.py --bhp_class $(bhp_class)
```

When running inspect, should show default with bhp_class = 0. Does not show anything
