### ISSUE TITLE
Design variable namespace 

### ISSUE THREAD

**Issue by haryle** [haryle/PyMake#58]

**Comment by harryle95** [comment]
## Local variable declaration:
- Allows for the same syntax used previously (all previous tests should still be compatible)
Example:
```
target:
  var:
    basic: {var1: null, var2: 100}
    option: {all: "-a"}
    sequence: [s1, s2]
  cmd:
    ...
```

- Variables can now be declared under `var`. 
- Variables declared under `var` can be a str, a list of string or mapping, or mappings.
- If variables provided as string or list of string, the type is defaulted to basic and required. 
- Mapping values can provide - `default` for default value, `type` for variable types. 

Example: all following examples are equivalent declarations and have the same effect as the previous example
```
target:
  var:
    - var1
    - var2
    - all: {type: "option", default: "-a"}
    - s1: {type: "sequence"}
    - s2: {type: "sequence"}
  cmd:
    ... 
```

```
target:
  var:
    var1: null
    var2: 100
    all: {type: "option", default: "-a"}
    s1: {type: "sequence"}
    s2: {type: "sequence"}
  cmd:
    ... 
```

```
target:
  var:
    var1: {type: basic, default: null}
    var2: 100
    all: {type: "option", default: "-a"}
    s1: {type: "sequence"}
    s2: {type: "sequence"}
  cmd:
    ... 
```

```
target:
  var:
    s1: {type: "sequence"}
    s2: {type: "sequence"}
    var1: {type: basic, default: null}
    var2: 100
    all: {type: "option", default: "-a"}
  cmd:
    ... 
```

**Comment by harryle95** [comment]
## Global variable declaration 

Simple global variables can be declared using:
- `Key`: `Value`
- `Key`: {"Value": <Value>, "Export": <T/F>}
The export keyword allows the key to be set as the environment variable 

Object based global variables can be declared using 
- Key:
    Field1: Value
    Field2: Value 
    ....
    Export: <T/F>

If export as an environment variable, the object will be serialised into a json-format string

**Comment by harryle95** [comment]
## Environment/Static declaration
- Either follows the format described in global variable declaration, or 
- `.Env`: `<dir>` where dir is directory to `.env` file. 

.env file follows python dotenv file syntax [here](https://pypi.org/project/python-dotenv/)

**Comment by harryle95** [comment]
## Local environment variable declaration:

- Declared under `env` field using `key`: `value` syntax, where value is a non-interpolated value, or an interpolating value, referencing a local, global, or static variable. The default scope search is local -> global -> static, but users can select global or static reference by adding the corresponding keyword. For example:

```
GLOBAL_VAR: 10
STATIC_VAR: 
  value: 100
  export: true

target:
  var:
    # This syntax is permitted, but not recommended. Global/static variables should be upper-case letters while 
    # local variables should be lower-cased. This example is for demonstration purposes only
    GLOBAL_VAR: 1000
    STATIC_VAR: 1000
  env:
    REF_LOCAL_GLOBAL: ${{GLOBAL_VAR}} # This will use the local GLOBAL_BAR
    REF_GLOBAL_GLOBAL: ${{global:GLOBAL_VAR}} # This will use the global GLOBAL_VAR
    REF_LOCAL_STATIC: ${{STATIC_VAR}}
    REF_STATIC_STATIC: ${{static:STATIC_VAR}}
  cmd:
    ...
```

- Declared under `.Env` field, with value specifying the directory. If an environment variable is declared under both `env` and `.Env`, the `env` value is used.
